---
# tasks file for SeiichiDomyo.libxfs

- hosts: centos7
  sudo: yes

  vars:
    util_linux_rpms_dir: /home/vagrant/rpmbuild/RPMS/x86_64
    util_linux_srpm: util-linux-2.23.2-26.el7.src.rpm
    util_linux_rpms:
       - filename: libuuid-devel-2.23.2-26.el7.x86_64.rpm
       - filename: libblkid-devel-2.23.2-26.el7.x86_64.rpm

  tasks:
    - stat: path=/usr/include/uuid/uuid.h
      register: _libuuid_devel

    - stat: path=/usr/include/blkid/blkid.h
      register: _libblkid_devel

    - name: install the 'Development tools' packages
      yum: name="@development" state=present

    - name: install some packages for rebuild
      yum: name={{ item }} state=present
      with_items:
        - yum-utils
        - rpmdevtools
        - readline-devel
        - audit-libs-devel
        - libselinux-devel
        - pam-devel
        - zlib-devel
        - popt-devel
        - libutempter-devel
        - systemd-devel
        - libuser-devel
        - libcap-ng-devel

    - name: download util-linux source
      sudo: no
      shell: rpm -ivh /vagrant/files/{{ util_linux_srpm }}
      when: ( _libuuid_devel.stat.exists  == false ) or
            ( _libblkid_devel.stat.exists == false ) 

    - name: build libuuid-devel and libblkid-devel 
      sudo: no
      shell: rpmbuild -ba --define="dist .el7" SPECS/util-linux.spec
      args:
        chdir: ~/rpmbuild/
      when: ( _libuuid_devel.stat.exists  == false ) or
            ( _libblkid_devel.stat.exists == false ) 

    - name: install libuuid-devel and libblkid-devel 
      yum: name="{{ util_linux_rpms_dir }}/{{ item.filename }}" state=present
      with_items: util_linux_rpms
      when: ( _libuuid_devel.stat.exists  == false ) or
            ( _libblkid_devel.stat.exists == false ) 
